project:
  type: website

website:
  title: "Mi Curso"
  description: "Descripci√≥n de tu curso"
  
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: lecciones/index.qmd
        text: Lecciones
    right:
      - icon: github
        href: https://github.com/tu-usuario/mi-curso

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    highlight-style: github

execute:
  freeze: auto
